import pygame

WIN_SIZE = 1200, 800
SCREEN_RECT = pygame.Rect((0, 0), WIN_SIZE)
MAX_IMAGE_WIDTH = 800
MAX_IMAGE_HEIGHT = 800
BUTTONS_JSON_FILE = 'buttons.json'

BUTTON_RADIUS = 4
BUTTON_SCREEN_COLLISION_DEFLATION = (-5, -5)
NORMAL_BUTTON_SPRITE_DEFLATION = (-8, -8)
ACTIVE_BUTTON_SPRITE_DEFLATION = (-3, -3)

